api/urls.py
from django.urls import path
from django.conf import settings
from api.LatexFinder import LatexFinder
import logging
import os
from api import ajax, models, views

app_name = 'api'

urlpatterns = [
    path('objects/', views.MathematicalObjectList.as_view(), name="mathematical_objects"),
    path('objects/<int:pk>/', views.MathematicalObjectDetail.as_view(), name="mathematical_object"),
    path('functions/', views.FunctionList.as_view(), name="functions"),
    path('functions/<int:pk>/', views.FunctionDetail.as_view(), name="function"),
    path('names/', views.NameList.as_view(), name="names"),
    path('names/<int:pk>/', views.NameDetail.as_view(), name="name"),
    path('tags/', views.TagList.as_view(), name="tags"),
    path('tags/<int:pk>/', views.TagDetail.as_view(), name="tag"),
    path('objects/<int:object_pk>/functions/', views.MathematicalObjectFunctionList.as_view(), name="mathematical_object_functions"),
    path('objects/<int:object_pk>/functions/<int:function_pk>', views.MathematicalObjectFunctionDetail.as_view(), name="mathematical_object_function"),
    path('objects/<int:object_pk>/names/', views.MathematicalObjectNameList.as_view(), name="mathematical_object_names"),
    path('objects/<int:object_pk>/names/<int:name_pk>', views.MathematicalObjectNameDetail.as_view(), name="mathematical_object_name"),
    path('objects/<int:object_pk>/related/', views.MathematicalObjectRelatedList.as_view(), name="mathematical_object_relations"),
    path('objects/<int:object_pk>/related/<int:other_pk>', views.MathematicalObjectRelatedDetail.as_view(), name="mathematical_object_relation"),
    path('objects/<int:object_pk>/tags/', views.MathematicalObjectTagList.as_view(), name="mathematical_object_tags"),
    path('objects/<int:object_pk>/tags/<int:tag_pk>', views.MathematicalObjectTagDetail.as_view(), name="mathematical_object_tag"),

    path('function-autocomplete/', ajax.FunctionAutocomplete.as_view(
        model=models.Function,
        create_field='function',
    ), name='function-autocomplete'),
    path('name-autocomplete/', ajax.NameAutocomplete.as_view(
        model=models.Name,
        create_field='name',
    ), name='name-autocomplete'),
    path('tag-autocomplete/', ajax.TagAutocomplete.as_view(
        model=models.Tag,
        create_field='tag',
    ), name='tag-autocomplete'),
]


def check_consistency(logger, objects, field, folder):
    existing = set()
    pointed = set()
    missing = []

    for object in objects:
        if field(object):
            path = field(object).name
            if os.path.isfile(path):
                pointed.add(path)
            else:
                missing.append(path)

    path = os.path.join(settings.MEDIA_ROOT, folder)
    for file in os.listdir(path):
        existing.add(os.path.join(settings.MEDIA_ROOT, folder, file))

    for m in missing:
        logger.error(f"Missing file: {m}")

    for m in existing.difference(pointed):
        logger.error(f"Existing file: {m} but not pointed by any")

    for m in pointed.difference(existing):
        logger.error(f"Pointed file: {m} but not existing")


def check_consistency_mathematical_objects(logger):
    check_consistency(logger, models.MathematicalObject.objects.all(), lambda x: x.description, 'mathematical_objects/')


def check_consistency_modifications(logger):
    check_consistency(logger, models.Modification.objects.all(), lambda x: x.new_description, 'modifications/')


def create_query_latex(logger):
    latex_finder = LatexFinder()
    for mathematical_object in models.MathematicalObject.objects.all():
        latex_finder.add(mathematical_object.pk, mathematical_object.latex)
    return latex_finder


def one_time_startup():
    logger = logging.getLogger(__name__)

    check_consistency_mathematical_objects(logger)
    check_consistency_modifications(logger)

    create_query_latex(logger)




one_time_startup()

front/urls.py
from django.urls import path

from . import views

app_name = 'front'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('functions/', views.FunctionListView.as_view(), name='functions'),
    path('functions/<int:pk>', views.FunctionDetailView.as_view(), name='function'),
    path('names/', views.NameListView.as_view(), name='names'),
    path('names/<int:pk>', views.NameDetailView.as_view(), name='name'),
    path('modifications/', views.ModificationListView.as_view(), name='modifications'),
    path('modifications/<int:pk>', views.modification_detail, name='modification'),
    path('object_creation/', views.create_mathematical_object, name='mathematical_object_creation'),
    path('object_edition/<int:pk>/', views.edit_mathematical_object, name='mathematical_object_edition'),
    path('objects/<int:pk>/description/', views.edit_mathematical_object_description, name='mathematical_object_description_edition'),
    path('objects/', views.MathematicalObjectListView.as_view(), name='mathematical_objects'),
    path('objects/<int:pk>/', views.MathematicalObjectDetailView.as_view(), name='mathematical_object'),
    path('propositions/', views.PropositionListView.as_view(), name='propositions'),
    path('proposition_creation/', views.create_proposition, name='proposition_creation'),
    path('proposition/<int:pk>/', views.proposition_detail, name='proposition'),
    path('tags/', views.TagListView.as_view(), name='tags'),
    path('tags/<int:pk>', views.TagDetailView.as_view(), name='tag'),
]

oems/urls.py
from django.contrib import admin
from django.urls import path
from rest_framework.authtoken import views
from django.conf.urls import include

from oems.views import create_token


urlpatterns = [
    path('', include('front.urls')),
    path('accounts/', include('django_registration.backends.activation.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('api/v1/', include('api.urls')),
    path('api-token-auth/', views.obtain_auth_token, name='api-token-auth'),
    path('api-token-create/', create_token, name='api-token-create'),
    path('markdownx/', include('markdownx.urls')),
]

api/models.py
from django.contrib.auth.models import User
from django.core.files.base import ContentFile
from django.db import models
from django.db.models.signals import post_delete, post_init, post_save
from django.dispatch import receiver

import logging
import os

from api.LatexFinder import LatexFinder
from api.model_config import *


def _delete_file(path):
    # Deletes file from filesystem.
    if os.path.isfile(path):
        os.remove(path)


class Function(models.Model):
    function = models.CharField(max_length=FUNCTION_REPRESENTATION_MAX_LENGTH)

    def __str__(self):
        return self.function


class Name(models.Model):
    name = models.CharField(max_length=NAME_REPRESENTATION_MAX_LENGTH)

    def __str__(self):
        return self.name


class Tag(models.Model):
    tag = models.CharField(max_length=TAG_REPRESENTATION_MAX_LENGTH)

    def __str__(self):
        return self.tag


class MathematicalObject(models.Model):
    latex = models.CharField(max_length=MATHEMATICAL_OBJECT_REPRESENTATION_MAX_LENGTH)
    type = models.CharField(max_length=1, choices=TYPE_CHOICES)
    related = models.ManyToManyField('self')
    functions = models.ManyToManyField(Function)
    names = models.ManyToManyField(Name)
    tags = models.ManyToManyField(Tag)
    convergence_radius = models.CharField(max_length=MATHEMATICAL_OBJECT_CONVERGENCE_RADIUS_MAX_LENGTH, blank=True)
    description = models.FileField(upload_to='mathematical_objects/', blank=True)
    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)

    def get_content(self):
        if not self.description:
            return ''

        try:
            with self.description.open(mode='r') as f:
                return f.read()
        except FileNotFoundError as e:
            logging.fatal('Mathematical object file not found for object: {}'.format(self.pk), exc_info=True)
            raise e

    def save_content(self, content):
        if self.description:
            with self.description.open(mode='w') as f:
                f.write(content)
        else:
            new_description_file = ContentFile(content)
            self.description.save(str(self.pk), new_description_file, save=True)

    def __str__(self):
        return str(self.id) + ' > ' + self.latex


@receiver(post_init, sender=MathematicalObject)
def remember_state(sender, **kwargs):
    instance = kwargs.get('instance')
    instance.previous_latex = instance.latex


@receiver(post_save, sender=MathematicalObject)
def update_latex_query(sender, **kwargs):
    instance = kwargs.get('instance')
    created = kwargs.get('created')
    if instance.previous_latex != instance.latex or created:
        latex_finder = LatexFinder()
        if not created:
            latex_finder.remove(instance.pk)
        latex_finder.add(instance.pk, instance.latex)


@receiver(post_delete, sender=MathematicalObject)
def delete_description_pre_delete_mathematical_object(sender, instance, *args, **kwargs):
    latex_finder = LatexFinder()
    latex_finder.remove(instance.pk)

    if instance.description:
        _delete_file(instance.description.path)


class Modification(models.Model):
    mathematical_object = models.ForeignKey(MathematicalObject, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date_created = models.DateField(auto_now=True)
    new_description = models.FileField(upload_to='modifications/')

    def get_content(self):
        if not self.new_description:
            return ''

        try:
            with self.new_description.open(mode='r') as f:
                return f.read()
        except FileNotFoundError as e:
            logging.fatal('Modification file not found for object: {}'.format(self.pk), exc_info=True)
            raise e


@receiver(post_delete, sender=Modification)
def delete_description_pre_delete_modification(sender, instance, *args, **kwargs):
    if instance.new_description:
        _delete_file(instance.new_description.path)


class Proposition(models.Model):
    content = models.TextField(max_length=PROPOSITION_REPRESENTATION_MAX_LENGTH)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date_created = models.DateField(auto_now=True)

front/models.py
from django.db import models

# Create your models here.

front/forms.py
from django import forms
from django.core.files.base import ContentFile

from api import models, validators
from front import widgets
from dal import autocomplete
from markdownx.widgets import MarkdownxWidget


class QueryForm(forms.Form):
    q = forms.CharField(required=False)


class MathematicalObjectForm(forms.ModelForm):
    description = forms.CharField(required=False, widget=MarkdownxWidget(attrs={'onkeyup': 'MathJax.Hub.Queue(["Typeset", MathJax.Hub])'}))

    class Meta:
        model = models.MathematicalObject
        fields = '__all__'

        widgets = {
            'latex': widgets.LatexInput(),
            'functions': autocomplete.ModelSelect2Multiple(url='api:function-autocomplete'),
            'names': autocomplete.ModelSelect2Multiple(url='api:name-autocomplete'),
            'tags': autocomplete.ModelSelect2Multiple(url='api:tag-autocomplete'),
        }

    def __init__(self, *args, **kwargs):
        super(MathematicalObjectForm, self).__init__(*args, **kwargs)
        self.fields['related'].required = False
        self.fields['functions'].required = False
        self.fields['names'].required = False
        self.fields['tags'].required = False

    def clean(self):
        super().clean()
        validators.validate_latex(self.cleaned_data.get('latex'))

    def save(self):
        super().save()
        description = self.cleaned_data['description']
        if description:
            description_file = ContentFile(description)
            self.instance.description.save(str(self.instance.pk), description_file, save=True)
        return self.instance


class ModificationForm(forms.Form):
    new_description = forms.CharField(required=True, widget=MarkdownxWidget(attrs={'onkeyup': 'MathJax.Hub.Queue(["Typeset", MathJax.Hub])'}))

    def save(self, mathematical_object, user):
        new_description_instance = models.Modification.objects.create(
            mathematical_object=mathematical_object,
            user=user
        )

        new_description = self.cleaned_data['new_description']
        if new_description:
            new_description_file = ContentFile(new_description)
            new_description_instance.new_description.save(str(new_description_instance.pk), new_description_file, save=True)
        return new_description_instance


class PropositionForm(forms.ModelForm):
    class Meta:
        model = models.Proposition
        fields = ('content', )

front/templates/front/about.html
{% extends "front/base.html" %}

{% block content %}

<section class="wrapper">
	<div class="inner">
		<header class="align-center">
            <h1>About the Online Encyclopedia of Mathematical Series</h1>
		</header>

		<div class="row">
            <section>
                <h3>Why this website ?</h3>
                <p>I realized that there were no real tools to research these mathematical forms. So I wanted to fill this gap by drawing inspiration from the excellent site of N. J. A. Sloane: <a href="https://oeis.org/">The On-Line Encyclopedia of Integer Sequences</a></p>
            </section>

            <section>
                <h3>What can you do ?</h3>
                <p>You can search according to 4 criteria:</p>
                <ol>
                    <li>The objects themselves by writing a formula in the form of latex. We will try to provide those with the closest structure possible.</li>
                    <li>The function is related to a general mathematical expression that is associated with the object and written in latex.</li>
                    <li>The names are the common ones associated with the formula.</li>
                    <li>The tag refers to the family to which the object belongs.</li>
                </ol>
                <p>Once you are on a mathematical object, you should be able to navigate from one to the other.</p>
            </section>

            <section>
                <h3>What can you specifically do ?</h3>
                <p>The possibilities offered by the website vary according to your status.</p>
                <h4>As a visitor:</h4>
                <p>You can freely consult the information available on this website but you will not be able to make any changes or suggest improvements.</p>
                <h4>As a user:</h4>
                <p>Once connected, you will be able to propose improvements and modifications to the text associated with each object. All changes will first be checked by team members to ensure that the content respects the spirit of the site. You can contact me if you wish to unregister.</p>
                <h4>As a staff member:</h4>
                <p>Staff members can accept or reject changes proposed by users. They can also modify the other elements attached to the objects or the text directly without passing a third party verification. It is a status reserved for serious people.</p>
            </section>

            <section>
                <h3>REST API ?</h3>
                <p>This website also offers an API REST that is intended for consultation only. This is more for computer scientists. It is available through the root: <a href="{% url 'api:mathematical_objects' %}">/api/v1/</a>, one may find more information on the associated github.
                </p>
            </section>

            <section>
                <h3>It's ugly and it's buggy !</h3>
                <p>I know ^^, you can always help me on the github.</p>
            </section>
        </div>
	</div>
</section>

{% endblock %}

front/templates/front/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>OEMS</title>
        <!-- Meta -->
        <meta http-equiv="content-type" content="text/html; charset=utf-8" />
        <meta name="description" content="Online Encyclopedia of Mathematical Series">
        <meta name="author" content="Youri Hubaut">
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <!-- Template CSS -->
        <link rel="stylesheet" href="{% static 'front/assets/css/main.css' %}"/>

        <!---->
        <script type="text/x-mathjax-config">
            MathJax.Hub.Config({
                tex2jax: {
                    inlineMath: [["$","$"],["\\(","\\)"]]
                },
            });
        </script>
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS_CHTML"></script>
        <!---->
    </head>
    <body class="subpage">

        <!-- Header -->
        <header id="header">
            <div class="inner">
                <a href="{% url 'front:index' %}" class="logo">OEMS</a>
                <nav id="nav">
                    <a href="{% url 'front:about' %}">About</a>
                    <a href="{% url 'front:mathematical_objects' %}">Objects</a>
                    <a href="{% url 'front:functions' %}">Functions</a>
                    <a href="{% url 'front:names' %}">Names</a>
                    <a href="{% url 'front:tags' %}">Tags</a>
                    {% if user.is_authenticated %}
                        {% if perms.api.delete_modification %}
                            <a href="{% url 'front:modifications' %}">Modifications</a>
                        {% endif %}
                        {% if perms.api.delete_proposition %}
                            <a href="{% url 'front:propositions' %}">Propositions</a>
                        {% else %}
                            <a href="{% url 'front:proposition_creation' %}">Propose</a>
                        {% endif %}
                        <a href="{% url 'logout'%}?next={{ request.path }}">Logout</a>
                    {% else %}
                        <a href="{% url 'login'%}?next={{ request.path }}">Login</a>
                    {% endif %}
                </nav>
                <a href="#navPanel" class="navPanelToggle"><span class="fa fa-bars"></span></a>
            </div>
        </header>
        {% block content %}{% endblock %}

        {% block pagination %}
            {% if is_paginated %}
                <div class="pagination">
                    <span class="step-links">
                        {% if page_obj.has_previous %}
                            <a href="{{ request.path }}?page=1">&laquo; first</a>
                            <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                        {% endif %}

                        <span class="current">
                            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                        </span>

                        {% if page_obj.has_next %}
                            <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
                            <a href="{{ request.path }}?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                        {% endif %}
                    </span>
                </div>
            {% endif %}
        {% endblock %}

        <script src="{% static 'front/assets/js/jquery.min.js' %}"></script>
        <script src="{% static 'front/assets/js/skel.min.js' %}"></script>
        <script src="{% static 'front/assets/js/util.js' %}"></script>
        <script src="{% static 'front/assets/js/main.js' %}"></script>
    </body>
</html>

front/templates/front/function.html
{% extends "front/base.html" %}

{% block content %}

<section id="main" class="wrapper">
	<div class="inner">
		<header class="align-center">
			<h2>Function: \( {{ function.function }} \)</h2>
		</header>

		<div class="table-wrapper">
			<table>
				{% for mathematical_object in function.mathematicalobject_set.all %}
					<tr>
						<td><a href="{% url 'front:mathematical_object' mathematical_object.pk %}">{{ mathematical_object.pk }}</a></td>
						<td>\( {{ mathematical_object.latex }} \)</td>
					</tr>
				{% empty %}
					Sorry, no mathematical objects related.
				{% endfor %}
			</table>
		</div>
	</div>
</section>

{% endblock %}

front/templates/front/functions.html
{% extends "front/base.html" %}

{% block content %}

<section id="main" class="wrapper">
	<div class="inner">
		<form action="" method="get">
			<div class="row uniform">
				<div class="2u"></div>
				<div class="8u align-center">
					{{ form.as_p }}
					<ul class="actions">
						<li><input type="submit" value="Search" class="button special" /></li>
					</ul>
				</div>
				<div class="2u"></div>
			</div>
		</form>

		<header>
			<h3>List of functions:</h3>
		</header>

		<div class="table-wrapper">
			{% if function_list %}
			<table>
				<thead>
					<tr>
						<th>ID</th>
						<th>Function name</th>
					</tr>
				</thead>

				<tbody>
				{% for function in function_list %}
					<tr>
						<td><a href="{% url 'front:function' function.pk %}">{{ function.pk }}</a></td>
						<td>\( {{ function.function }} \)</td>
					</tr>
				{% endfor %}
				</tbody>
			</table>
			{% else %}
				Sorry, no functions available.
			{% endif %}
		</div>
	</div>
</section>

{% endblock %}

front/templates/front/index.html
{% extends "front/base.html" %}

{% load staticfiles %}

{% block content %}

	<!-- === BEGIN CONTENT === -->
	<section id="main" class="wrapper">
		<div class="inner">
			<header class="align-center">
				<h2>Welcome to OEMS</h2>
				<p>The Online Encyclopedia of Mathematical Series containing <i>{{ number_series }}</i> mathematical objects.</p>
			</header>

			<form action="{% url 'front:mathematical_objects' %}" method="get">
				<div class="row uniform">
					<div class="2u"></div>
					<div class="8u align-center">
						{{ form.as_p }}
						<ul class="actions">
							<li><input type="submit" value="Search" class="button special" /></li>
						</ul>
					</div>
					<div class="2u"></div>
				</div>
			</form>

			<div class="row">
				<section>
					<h3>Find</h3>
					<p>You can use the main menu to move through the 3 principal concepts of this website. You will find a list of all the elements related where you can access each of them individually to get more information. You can also perform searches to refine your results either by inserting words in the case of names or by typing an expression in the form of LaTeX language.</p>
				</section>

				<section>
					<h3>Contribute & Improve</h3>
					<p>You can contribute to the project by proposing new mathematical objects to be added or by posting modifications to the explanatory text associated with each element.</br>
						For those with some graphic or programming skills, it is possible to contribute and improve the project through the associated <a href="https://github.com/Gawaboumga/OEMS">Github repository</a>.</br>
						You can also give some ideas to improve the website or report bugs, directly by the list of propositions or on the github page of the project.</p>
				</section>
			</div>
		</div>
	</section>

{% endblock %}

front/templates/front/mathematical_object.html
{% extends "front/base.html" %}
{% load front_filters %}

{% block content %}

<section id="main" class="wrapper">
	<div class="inner">
		<div class="align-right">
			{% if perms.api.change_mathematicalobject %}
				<a href="{% url 'front:mathematical_object_edition' mathematical_object.pk %}" class="button special">Edit info</a>
			{% endif %}
		</div>

		<header class="align-center">
			{% if mathematical_object.type == 'S' %}
				<h2>Series #{{ mathematical_object.id }}</h2>
			{% elif mathematical_object.type == 'P' %}
				<h2>Euler product #{{ mathematical_object.id }}</h2>
			{% elif mathematical_object.type == 'K' %}
				<h2>Continued fraction #{{ mathematical_object.id }}</h2>
			{% endif %}
			<p>\( {{ mathematical_object.latex }} \)</p>
		</header>

		{% if mathematical_object.names %}
		<div class="row">
			<div class="12u">
				<p>
					Associated names:
					{% for name in mathematical_object.names.all %}
						<a href="{% url 'front:name' name.id %}">{{ name.name }}</a>
						{% if not forloop.last %}, {% endif %}
					{% endfor %}
				</p>
			</div>
		</div>
		{% endif %}

		{% if mathematical_object.functions %}
		<div class="row">
			<div class="12u">
				<p>
					Associated functions:
					{% for function in mathematical_object.functions.all %}
						<a href="{% url 'front:function' function.id %}">\( {{ function.function }} \)</a>
						{% if not forloop.last %}, {% endif %}
					{% endfor %}
				</p>
			</div>
		</div>
		{% endif %}

		{% if mathematical_object.tags %}
		<div class="row">
			<div class="12u">
				<p>
					Associated tags:
					{% for tag in mathematical_object.tags.all %}
						<a href="{% url 'front:tag' tag.id %}">{{ tag.tag }}</a>
						{% if not forloop.last %}, {% endif %}
					{% endfor %}
				</p>
			</div>
		</div>
		{% endif %}

		{% if mathematical_object.related %}
		<div class="row">
			<div class="12u">
				<p>
					Related objects:
					{% for related_object in mathematical_object.related.all %}
						<a href="{% url 'front:mathematical_object' related_object.id %}">\( {{ related_object.latex }} \)</a>
						{% if not forloop.last %}, {% endif %}
					{% endfor %}
				</p>
			</div>
		</div>
		{% endif %}


		{% if mathematical_object.description %}
		<div class="row">
			<div class="12u">

				<div class="box">
					{{ mathematical_object.get_content|show_markdown|safe }}
				</div>
			</div>
		</div>
		{% endif %}


		{% if user.is_authenticated %}
			<div class="align-right">
				<a href="{% url 'front:mathematical_object_description_edition' mathematical_object.pk %}" class="button special">Edit description</a>
			</div>
		{% endif %}

		<div class="row">
			Created on: {{ mathematical_object.date_created }}. Last update: {{ mathematical_object.date_updated }}
		</div>
	</div>
</section>





{% endblock %}

front/templates/front/mathematical_objects.html
{% extends "front/base.html" %}

{% block content %}

<section id="main" class="wrapper">
	<div class="inner">
		<form action="" method="get">
			<div class="row uniform">
				<div class="2u"></div>
				<div class="8u align-center">
					{{ form.as_p }}
					<ul class="actions">
						<li><input type="submit" value="Search" class="button special" /></li>
					</ul>
				</div>
				<div class="2u"></div>
			</div>
		</form>

		<header>
			<h3>List of mathematical objects:</h3>
		</header>

		<div class="table-wrapper">
			{% if mathematical_objects %}
			<table>
				<thead>
					<tr>
						<th>ID</th>
						<th>Expression</th>
					</tr>
				</thead>

				<tbody>
				{% for mathematical_object in mathematical_objects %}
					<tr>
						<td><a href="{% url 'front:mathematical_object' mathematical_object.pk %}">{{ mathematical_object.pk }}</a></td>
						<td>\( {{ mathematical_object.latex }} \)</td>
					</tr>
				{% endfor %}
				</tbody>
			</table>
			{% else %}
				Sorry, no mathematical objects available.
			{% endif %}
		</div>

		<div class="align-right">
			{% if user.is_authenticated and perms.api.add_mathematicalobject %}
				<a href="{% url 'front:mathematical_object_creation' %}" class="button">Add</a>
			{% endif %}
		</div>
	</div>
</section>

{% endblock %}

front/templates/front/modification.html
{% extends "front/base.html" %}
{% load front_filters %}

{% block content %}

<div class="wrapper">
	<div class="inner">
		<header class="align-center">
			<h2>From user: {{ modification.user }} for mathematical object: <a href="{% url 'front:mathematical_object' modification.mathematical_object.pk %}">{{ modification.mathematical_object.pk }}</a></h2>
		</header>

		<div class="row">
			<section class="12u">
				<h2>Old content:</h2>
				{% if modification.mathematical_object.get_content %}
					<div class="box">
						{{ modification.mathematical_object.get_content|show_markdown|safe }}
					</div>
				{% else %}
					<p>Content was empty.</p>
				{% endif %}
			</section>
		</div>

		<div class="row">
			<section class="12u">
				<h2>New content:</h2>
				<div class="box">
					{{ modification.get_content|show_markdown|safe }}
				</div>
			</section>
		</div>

		<div class="row">
			<section class="12u">
				<form action="" method="post">
					{% csrf_token %}
					{{ form_accept }}
					<div class="align-right">
						{% if perms.api.delete_modification %}
							<input type="submit" name="accept_modification" value="Accept" />
							<input type="submit" name="reject_modification" value="Reject" />
						{% else %}
							<input type="submit" name="reject_modification" value="Delete" />
						{% endif %}
					</div>
				</form>
			</section>
		</div>
	</div>
</section>

{% endblock %}

front/templates/front/modifications.html
{% extends "front/base.html" %}

{% block content %}

<section id="main" class="wrapper">
	<div class="inner">
		<header>
			<h3>List of modifications:</h3>
		</header>

		<div class="table-wrapper">
			{% if modifications %}
			<table>
				<thead>
					<tr>
						<th>ID</th>
						<th>Created on:</th>
						<th>By user:</th>
					</tr>
				</thead>

				<tbody>
				{% for modification in modifications %}
				<tr>
					<td><a href="{% url 'front:modification' modification.pk %}">{{ modification.pk }}</a></td>
					<td>{{ modification.date_created }}</td>
					<td>{{ modification.user }}</td>
				</tr>
				{% endfor %}
				</tbody>
			</table>
			{% else %}
				Sorry, no modifications available.
			{% endif %}
		</div>
	</div>
</section>

{% endblock %}

front/templates/front/propositions.html
{% extends "front/base.html" %}

{% block content %}

<section id="main" class="wrapper">
	<div class="inner">
		<header>
			<h3>List of propositions:</h3>
		</header>

		<div class="table-wrapper">
			{% if propositions %}
			<table>
				<thead>
					<tr>
						<th>ID</th>
						<th>Created on:</th>
						<th>By user:</th>
					</tr>
				</thead>

				<tbody>
				{% for proposition in propositions %}
				<tr>
					<td><a href="{% url 'front:proposition' proposition.pk %}">{{ proposition.pk }}</a></td>
					<td>{{ proposition.date_created }}</td>
					<td>{{ proposition.user }}</td>
				</tr>
				{% endfor %}
				</tbody>
			</table>
			{% else %}
				Sorry, no propositions available.
			{% endif %}
		</div>

		<div class="align-right">
			<a href="{% url 'front:proposition_creation' %}" class="button">Propose</a>
		</div>
	</div>
</section>

{% endblock %}

front/templates/front/tag.html
{% extends "front/base.html" %}

{% block content %}

<section id="main" class="wrapper">
	<div class="inner">
		<header class="align-center">
			<h2>Tag: {{ tag.tag }}</h2>
		</header>

		<div class="table-wrapper">
			<table>
				{% for mathematical_object in tag.mathematicalobject_set.all %}
					<tr>
						<td><a href="{% url 'front:mathematical_object' mathematical_object.pk %}">{{ mathematical_object.pk }}</a></td>
						<td>\( {{ mathematical_object.latex }} \)</td>
					</tr>
				{% empty %}
					Sorry, no mathematical objects related.
				{% endfor %}
			</table>
		</div>
	</div>
</section>

{% endblock %}